let ok = function Ok()->() | Error e->failwith e
let add t time value=ok(Window.add t ~time ~value)
let () = match Sys.argv.(1) with
| "empty_limits" -> let t=Window.create ~width:4 in assert(Window.count t=0); assert(Window.total t=0); assert(Window.watermark t=None); assert(Window.add t ~time:(-1) ~value:1=Error "negative time"); (try ignore(Window.create ~width:0); assert false with Invalid_argument _->())
| "expire_late" -> let t=Window.create ~width:3 in add t 10 5; add t 8 2; add t 9 (-1); add t 11 4; assert(Window.count t=3); assert(Window.total t=8); let before=Window.bucket_visits t in assert(Window.add t ~time:8 ~value:100=Error "late event"); assert(Window.total t=8); assert(Window.bucket_visits t=before)
| "out_of_order" -> let t=Window.create ~width:4 in add t 10 3; add t 7 5; add t 9 (-2); add t 7 4; add t 11 1; assert(Window.count t=3); assert(Window.total t=2); assert(Window.watermark t=Some 11)
| "huge_jump" -> let t=Window.create ~width:7 in add t 0 4; let before=Window.bucket_visits t in add t max_int 8; assert(Window.total t=8); assert(Window.count t=1); assert(Window.bucket_visits t-before<=8); assert(Window.add t ~time:0 ~value:1=Error "late event")
| "reference_workload" -> let rng=Random.State.make [|112;39|] in let t=Window.create ~width:17 in let history=ref [] and w=ref 0 in for i=1 to 800 do let time= !w+Random.State.int rng 10-4 in let value=Random.State.int rng 19-9 in let expected=if time<0 then Error "negative time" else if time < max 0 (!w-16) then Error "late event" else Ok() in assert(Window.add t ~time ~value=expected); if expected=Ok() then begin w:=max !w time; history:=(time,value):: !history end; let live=List.filter(fun(tm,_)->tm>=max 0 (!w-16)) !history in assert(Window.count t=List.length live); assert(Window.total t=List.fold_left(fun a (_,v)->a+v) 0 live); ignore i done
| "allocation_work" -> let width=1024 in let t=Window.create ~width in for i=0 to 2047 do add t i 1 done; Gc.full_major(); let before=Gc.allocated_bytes() in for i=2048 to 52047 do match Window.add t ~time:i ~value:1 with Ok()->() | Error e->failwith e done; let bytes=Gc.allocated_bytes()-.before in Printf.printf "bytes/event=%.3f visits=%d\n" (bytes/.50000.) (Window.bucket_visits t); assert(bytes/.50000.<32.); assert(Window.bucket_visits t <= 3*52048+2*width); assert(Window.count t=width); assert(Window.total t=width)
| _->failwith "unknown case"
