#!/usr/bin/env python3
"""Export one VulcanBench Frontier v4 task directory to Harbor task format.

Converts a VulcanBench task directory (issue.md, repo/, tests/, metadata.json)
into a Harbor task directory (instruction.md, task.toml, environment/, tests/)
as consumed by github.com/harbor-framework/harbor. See
scripts/harbor-export/README.md for the format mapping and the sources for
every schema claim.

Usage::

    python scripts/harbor-export/export_task.py \\
        tasks/coding-intelligence-index-v4/legacy-granarycore-binary-parity \\
        exports/harbor/legacy-granarycore-binary-parity

Integrity rules enforced here:

- ``builder/`` (secret C source and gold implementation) and
  ``gold_patch.diff`` (reference solution) are never copied; after writing,
  the output tree is scanned and the export fails if either leaked.
- The verifier phase is declared ``network_mode = "no-network"`` so grading
  runs with the network off.
- The pytest suite lands in Harbor's ``tests/`` directory, which the Harbor
  harness uploads to ``/tests`` in the container only AFTER the agent phase
  (shared verifier mode), so the agent never sees fixtures or expected
  outputs during its run.
- ``--with-solution`` adds ``solution/solve.sh`` (the gold patch, applied on
  the host and shipped as the patched files) for Harbor's ``oracle`` agent.
  It is for local scoring checks only and must never be published.
"""

from __future__ import annotations

import argparse
import json
import shutil
import stat
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

DEFAULT_ORG = "vulcanbench"
BASE_IMAGE = "python:3.12-slim"
# Every task ships a linux-amd64 reference binary the agent is expected to
# run, and task.toml has no architecture field, so the Dockerfile pins it.
PLATFORM = "linux/amd64"
PYTEST_PIN = "9.1.1"
WORKSPACE_DIR = "/app"

# Files/dirs in a source task dir that must NEVER reach an export.
SECRET_ENTRIES = ("builder", "gold_patch.diff")


def _canary_line(metadata: dict, comment: str = "#") -> str:
    canary = metadata.get("canary", "")
    return f"{comment} {canary}".rstrip()


def _load_source(task_dir: Path) -> dict:
    metadata = json.loads((task_dir / "metadata.json").read_text(encoding="utf-8"))
    issue = (task_dir / "issue.md").read_text(encoding="utf-8")
    if not (task_dir / "repo").is_dir():
        raise SystemExit(f"missing repo/ in {task_dir}")
    if not (task_dir / "tests").is_dir():
        raise SystemExit(f"missing tests/ in {task_dir}")
    return {"metadata": metadata, "issue": issue}


def _test_modules(task_dir: Path) -> list[str]:
    """Test module filenames referenced by metadata test commands, in run order.

    Regression guards (pass_to_pass) first, then fail_to_pass, deduplicated.
    """
    metadata = json.loads((task_dir / "metadata.json").read_text(encoding="utf-8"))
    tests = metadata.get("tests", {})
    modules: list[str] = []
    for group in ("pass_to_pass", "fail_to_pass"):
        for entry in tests.get(group, []):
            cmd = entry.get("cmd", "")
            for token in cmd.split():
                if "::" in token:
                    module = token.split("::")[0]
                    if module.endswith(".py") and module not in modules:
                        modules.append(module)
    if not modules:
        raise SystemExit("could not derive test modules from metadata tests commands")
    return modules


def _verifier_timeout_sec(metadata: dict) -> float:
    """Map our per-test-command timeout to Harbor's single-run verifier timeout.

    Our harness allows ``test_timeout_s`` for EACH test command; Harbor runs
    the whole suite in one ``tests/test.sh`` invocation, so the equivalent
    upper bound is test_timeout_s times the number of test commands.
    """
    per_test = metadata.get("test_timeout_s", 600)
    tests = metadata.get("tests", {})
    n = len(tests.get("fail_to_pass", [])) + len(tests.get("pass_to_pass", []))
    return float(per_test * max(n, 1))


def _agent_timeout_sec(metadata: dict) -> float:
    hints = metadata.get("agent_hints", {})
    timeout = hints.get("suggested_timeout_s")
    if not timeout:
        raise SystemExit("metadata.json has no agent_hints.suggested_timeout_s")
    return float(timeout)


def _toml_str(value: str) -> str:
    return json.dumps(value)  # JSON string escaping is valid TOML


def _render_task_toml(metadata: dict, org: str) -> str:
    task_id = metadata["id"]
    name = f"{org}/{task_id}"
    description = (
        f"VulcanBench Frontier v4 task {task_id} "
        f"({metadata.get('category', 'unknown')}, "
        f"difficulty {metadata.get('difficulty', 'unknown')}). "
        "Harbor export generated by scripts/harbor-export/export_task.py."
    )
    languages = metadata.get("languages", [])
    keywords = [metadata.get("category", "coding"), *languages]
    lines = [
        _canary_line(metadata),
        "",
        'schema_version = "1.4"',
        "",
        "[task]",
        f"name = {_toml_str(name)}",
        'version = "1.0.0"',
        f"description = {_toml_str(description)}",
        'authors = [{ name = "VulcanBench", email = "morgan@vulcanbench.com" }]',
        f"keywords = {json.dumps(keywords)}",
        "",
        "[metadata]",
        f"vulcanbench_task_id = {_toml_str(task_id)}",
        'vulcanbench_suite = "coding-intelligence-index-v4"',
        f"category = {_toml_str(metadata.get('category', ''))}",
        f"difficulty = {_toml_str(metadata.get('difficulty', ''))}",
        f"languages = {json.dumps(languages)}",
        f"canary = {_toml_str(metadata.get('canary', ''))}",
        "",
        "[agent]",
        # Our uniform flat timeout (metadata agent_hints.suggested_timeout_s; 3 hours since 2026-09-13).
        f"timeout_sec = {_agent_timeout_sec(metadata)}",
        "",
        "[verifier]",
        # Shared mode (no [verifier.environment], no environment_mode): the
        # pytest suite runs in the agent's container, uploaded to /tests only
        # after the agent phase ends. Grading runs with the network off.
        f"timeout_sec = {_verifier_timeout_sec(metadata)}",
        'network_mode = "no-network"',
        "",
        "[environment]",
        "build_timeout_sec = 900.0",
        "cpus = 2",
        "memory_mb = 4096",
        "storage_mb = 10240",
        "",
    ]
    return "\n".join(lines)


def _render_instruction(issue: str) -> str:
    note = (
        f"\nThe project workspace is at `{WORKSPACE_DIR}` inside the "
        "container (the paths above are relative to it).\n"
    )
    return issue.rstrip("\n") + "\n" + note


def _repo_executables(repo_dir: Path) -> list[str]:
    """Relative paths of executable files in repo/, for a defensive chmod."""
    out: list[str] = []
    for path in sorted(repo_dir.rglob("*")):
        if path.is_file() and path.stat().st_mode & stat.S_IXUSR:
            out.append(path.relative_to(repo_dir).as_posix())
    return out


def _render_dockerfile(metadata: dict, repo_dir: Path) -> str:
    chmod_lines = ""
    executables = _repo_executables(repo_dir)
    if executables:
        targets = " ".join(f"{WORKSPACE_DIR}/{p}" for p in executables)
        chmod_lines = (
            "\n# Defensive: re-assert the executable bits COPY should preserve.\n"
            f"RUN chmod +x {targets}\n"
        )
    return f"""{_canary_line(metadata)}
# repo/legacy/ ships a linux-amd64 reference binary that the agent is expected
# to run, so the image is pinned to linux/amd64 (emulated on arm64 hosts).
FROM --platform={PLATFORM} {BASE_IMAGE}

# The verifier runs in this same container (Harbor shared verifier mode), so
# pytest is baked in at build time: no network installs at verify time.
RUN pip install --no-cache-dir pytest=={PYTEST_PIN}

COPY repo/ {WORKSPACE_DIR}/
{chmod_lines}
WORKDIR {WORKSPACE_DIR}
"""


def _render_test_sh(metadata: dict, modules: list[str]) -> str:
    module_args = " ".join(f"/tests/{m}" for m in modules)
    return f"""#!/usr/bin/env bash
{_canary_line(metadata)}
# Harbor verifier entrypoint. The Harbor harness uploads this task's tests/
# directory to /tests after the agent phase and executes this script; reward
# is reported by writing /logs/verifier/reward.txt (1 = solved, 0 = not).
set -uo pipefail

LOG_DIR="${{VERIFIER_LOG_DIR:-/logs/verifier}}"
mkdir -p "$LOG_DIR"

# Re-root the workspace into the container's writable layer. The workspace is
# COPYed into an image layer, and overlayfs refuses directory renames of
# lower-layer directories (EXDEV, "Invalid cross-device link"), which breaks
# the test suite's legacy/ quarantine fixture. Rebuilding the tree at runtime
# (capturing any agent modifications) makes every path upper-layer.
cd /
cp -a {WORKSPACE_DIR} {WORKSPACE_DIR}.verify
rm -rf {WORKSPACE_DIR}
mv {WORKSPACE_DIR}.verify {WORKSPACE_DIR}

# Run from the workspace, as our grader does (PYTHONPATH=. included):
# conftest.py resolves the workspace as Path.cwd() and invokes the agent's
# module there. --rootdir pins pytest's rootdir to /tests so conftest.py is
# always picked up despite -c /dev/null. One pytest run covers every
# fail_to_pass and pass_to_pass test; reward is all-or-nothing, as in ours.
cd {WORKSPACE_DIR}
PYTHONPATH=. python -m pytest -c /dev/null -p no:cacheprovider --rootdir=/tests -q {module_args}
if [ $? -eq 0 ]; then
  echo 1 > "$LOG_DIR/reward.txt"
else
  echo 0 > "$LOG_DIR/reward.txt"
fi
"""


def _render_solve_sh(metadata: dict, files: list[str], deleted: list[str]) -> str:
    lines = [
        "#!/usr/bin/env bash",
        _canary_line(metadata),
        "# Oracle solution for Harbor's `oracle` agent: the gold patch, applied at",
        "# export time and shipped as the patched files. Local checks only.",
        "set -euo pipefail",
        f"cd {WORKSPACE_DIR}",
    ]
    lines += [f"cp /solution/files/{f} {WORKSPACE_DIR}/{f}" for f in files]
    lines += [f"rm -f {WORKSPACE_DIR}/{f}" for f in deleted]
    return "\n".join(lines) + "\n"


def _write_solution(task_dir: Path, metadata: dict, out_dir: Path) -> None:
    """Apply gold_patch.diff to a scratch copy of repo/ and ship the result."""
    with tempfile.TemporaryDirectory() as tmp:
        patched = Path(tmp) / "repo"
        shutil.copytree(task_dir / "repo", patched)
        subprocess.run(
            ["patch", "-p1", "--batch", "--silent", "-d", str(patched)],
            input=(task_dir / "gold_patch.diff").read_bytes(),
            check=True,
        )
        before = {p.relative_to(task_dir / "repo").as_posix() for p in (task_dir / "repo").rglob("*") if p.is_file()}
        after = {p.relative_to(patched).as_posix() for p in patched.rglob("*") if p.is_file()}
        changed = sorted(
            f for f in after
            if f not in before or (patched / f).read_bytes() != (task_dir / "repo" / f).read_bytes()
        )
        deleted = sorted(before - after)
        if not changed and not deleted:
            raise SystemExit(f"gold patch changed nothing in {task_dir.name}")
        files_dir = out_dir / "solution" / "files"
        for f in changed:
            (files_dir / f).parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(patched / f, files_dir / f)
    solve = out_dir / "solution" / "solve.sh"
    solve.write_text(_render_solve_sh(metadata, changed, deleted), encoding="utf-8")
    solve.chmod(solve.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def _assert_no_secrets(out_dir: Path) -> None:
    leaked = []
    if (out_dir / "solution").exists():
        leaked.append(out_dir / "solution")
    for path in out_dir.rglob("*"):
        name = path.name
        if name in SECRET_ENTRIES:
            leaked.append(path)
        if path.is_dir():
            continue
        if name.startswith("gold_") or name.endswith(".c"):
            leaked.append(path)
    if leaked:
        raise SystemExit(f"secret material leaked into export: {leaked}")


def export_task(
    task_dir: Path, out_dir: Path, org: str = DEFAULT_ORG, with_solution: bool = False
) -> None:
    source = _load_source(task_dir)
    metadata = source["metadata"]
    modules = _test_modules(task_dir)

    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)

    (out_dir / "instruction.md").write_text(_render_instruction(source["issue"]), encoding="utf-8")

    task_toml = _render_task_toml(metadata, org)
    tomllib.loads(task_toml)  # syntax sanity check before writing
    (out_dir / "task.toml").write_text(task_toml, encoding="utf-8")

    env_dir = out_dir / "environment"
    env_dir.mkdir()
    shutil.copytree(task_dir / "repo", env_dir / "repo")
    (env_dir / "Dockerfile").write_text(
        _render_dockerfile(metadata, task_dir / "repo"), encoding="utf-8"
    )

    tests_dir = out_dir / "tests"
    shutil.copytree(task_dir / "tests", tests_dir)
    test_sh = tests_dir / "test.sh"
    test_sh.write_text(_render_test_sh(metadata, modules), encoding="utf-8")
    test_sh.chmod(test_sh.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    # Scan before the optional oracle solution is added, so the public part
    # of every export is checked the same way.
    _assert_no_secrets(out_dir)
    if with_solution:
        _write_solution(task_dir, metadata, out_dir)
    print(f"exported {task_dir.name} -> {out_dir}" + (" (with oracle solution)" if with_solution else ""))


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("task_dir", type=Path, help="source task dir (contains metadata.json)")
    p.add_argument("out_dir", type=Path, help="output Harbor task dir (recreated)")
    p.add_argument("--org", default=DEFAULT_ORG, help="Harbor org prefix for [task].name")
    p.add_argument(
        "--with-solution",
        action="store_true",
        help="add solution/solve.sh from the gold patch (local oracle checks only; never publish)",
    )
    args = p.parse_args(argv)

    if not (args.task_dir / "metadata.json").is_file():
        p.error(f"{args.task_dir} is not a task dir (no metadata.json)")
    if args.out_dir.resolve().is_relative_to(args.task_dir.resolve()):
        p.error("out_dir must not be inside the source task dir")
    export_task(args.task_dir, args.out_dir, args.org, args.with_solution)
    return 0


if __name__ == "__main__":
    sys.exit(main())
