"""Suite locks: a published suite's scoring-relevant content cannot drift.

Freezing a suite writes ``tasks/<suite>/suite.lock.json``: the suite's version
(from its ``suite.json``) and the ``task_hash`` of every task in it. ``check``
fails if any locked suite no longer matches, so CI rejects a PR that edits a
published task in place. Cosmetic metadata is outside ``task_hash`` and stays
editable; the prompt, repo, tests, verifier, gold patch or the task set are not.

Changing a frozen suite on purpose means bumping ``version`` in its suite.json
and re-freezing, in the same PR. Results are comparable only within a version
(tasks/coding-intelligence-index-v4/CHARTER.md). See docs/HOW_WE_WORK.md.

    python -m harness.suite_lock check
    python -m harness.suite_lock freeze coding-intelligence-index-v4
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from harness.suite import DEFAULT_TASKS_BASE, load_suite
from harness.tasks import load_task, task_hash

LOCK_NAME = "suite.lock.json"


def suite_version(tasks_root: Path) -> str | None:
    manifest = tasks_root / "suite.json"
    if not manifest.is_file():
        return None
    version = json.loads(manifest.read_text(encoding="utf-8")).get("version")
    return str(version) if version is not None else None


def compute_lock(name: str, tasks_base: Path = DEFAULT_TASKS_BASE) -> dict[str, Any]:
    suite = load_suite(name, tasks_base)
    return {
        "suite": suite.name,
        "version": suite_version(suite.tasks_root),
        "tasks": {tid: task_hash(load_task(tid, suite.tasks_root)) for tid in suite.task_ids},
    }


def freeze(name: str, tasks_base: Path = DEFAULT_TASKS_BASE) -> Path:
    lock = compute_lock(name, tasks_base)
    out = {
        "suite": lock["suite"],
        "version": lock["version"],
        "frozen_at": datetime.now(UTC).date().isoformat(),
        "note": (
            "Generated by python -m harness.suite_lock freeze. Do not edit by hand. "
            "To change this suite, bump version in suite.json and re-freeze in the "
            "same PR (docs/HOW_WE_WORK.md)."
        ),
        "tasks": lock["tasks"],
    }
    path = tasks_base / str(lock["suite"]) / LOCK_NAME
    path.write_text(json.dumps(out, indent=2) + "\n", encoding="utf-8")
    return path


@dataclass
class LockDrift:
    suite: str
    problems: list[str] = field(default_factory=list)


def check_suite(name: str, tasks_base: Path = DEFAULT_TASKS_BASE) -> LockDrift:
    locked = json.loads((tasks_base / name / LOCK_NAME).read_text(encoding="utf-8"))
    current = compute_lock(name, tasks_base)
    drift = LockDrift(suite=name)
    if locked.get("version") != current["version"]:
        drift.problems.append(
            f"version is {current['version']!r} in suite.json but {locked.get('version')!r} "
            "in the lock: re-freeze after a version bump"
        )
        return drift
    old: dict[str, str] = locked.get("tasks") or {}
    new: dict[str, str] = current["tasks"]
    for tid in sorted(set(new) - set(old)):
        drift.problems.append(f"task added: {tid}")
    for tid in sorted(set(old) - set(new)):
        drift.problems.append(f"task removed: {tid}")
    for tid in sorted(set(old) & set(new)):
        if old[tid] != new[tid]:
            drift.problems.append(f"task changed: {tid}")
    return drift


def locked_suites(tasks_base: Path = DEFAULT_TASKS_BASE) -> list[str]:
    return sorted(p.parent.name for p in tasks_base.glob(f"*/{LOCK_NAME}"))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m harness.suite_lock", description=__doc__)
    parser.add_argument("--tasks-base", type=Path, default=DEFAULT_TASKS_BASE)
    sub = parser.add_subparsers(dest="cmd", required=True)
    p_check = sub.add_parser("check", help="verify locked suites (all, or the ones named)")
    p_check.add_argument("suites", nargs="*")
    p_freeze = sub.add_parser("freeze", help="write or refresh a suite's lock")
    p_freeze.add_argument("suite")
    args = parser.parse_args(argv)

    if args.cmd == "freeze":
        path = freeze(args.suite, args.tasks_base)
        print(f"froze {path}")
        return 0

    names = args.suites or locked_suites(args.tasks_base)
    failed = False
    for name in names:
        drift = check_suite(name, args.tasks_base)
        if drift.problems:
            failed = True
            print(f"FAIL {name}")
            for problem in drift.problems:
                print(f"  {problem}")
        else:
            print(f"ok   {name}")
    if failed:
        print(
            "\nA frozen suite changed. If that is intended, bump version in its suite.json "
            "and run: python -m harness.suite_lock freeze <suite>\n"
            "If you changed nothing, look for ignored or untracked files inside the task "
            "dirs (git status --ignored tasks/<suite>); task_hash counts every file "
            "under repo/ and tests/ except local byproducts such as __pycache__ and "
            ".DS_Store. A fresh checkout or run worktree is the reference.",
            file=sys.stderr,
        )
    return 1 if failed else 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
